#!/bin/bash
re='^[0-9]+$'

if [ -z "$1" ] || [ -z "$2" ] || ! [[ $2 =~ $re ]] ; then
   printf "Generate key with provided certificate common name,\nwith custom expiration date\nand export it to pkcs12 format\n\n Usage: $0 <cert_common_name> <days_to_expire> \n(for example: $0 test.navigat.ru 30)\n"
      exit 1
fi
source ./vars
export KEY_EXPIRE=$2
export EASY_RSA="${EASY_RSA:-.}"
"$EASY_RSA/pkitool" --interact --pkcs12 $1

#openssl pkcs12 -in "/usr/share/easy-rsa/2.0/keys/avis.navigat.ru.crt" -inkey "/usr/share/easy-rsa/2.0/keys/avis.navigat.ru.key" -export -name "avis.navigat.ru" -out "avis.navigat.ru.p12" -certfile "/usr/share/easy-rsa/2.0/keys/ca.crt"
