#!/bin/bash
[ -z "$1" ] && printf " Revoke key with provided certificate common name\n and move it to key/revoked folder\n\n Usage: $0 <cert_common_name> (for example: $0 test.navigat.ru)\n" && exit
source ./vars
export EASY_RSA="${EASY_RSA:-.}"
cd "$EASY_RSA/keys"
"$EASY_RSA/revoke-full" $1
mv $1.* "$EASY_RSA/keys/revoked"
cp -f $EASY_RSA/keys/crl.pem /etc/openvpn/srv/